addSbtPlugin("org.foundweekends"         % "sbt-bintray"   % "0.5.3")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"      % "1.4.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-ghpages"   % "0.6.3")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.9.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.12")
