addSbtPlugin("com.geirsson"              % "sbt-ci-release"  % "1.5.7")
addSbtPlugin("com.typesafe.sbt"          % "sbt-ghpages"     % "0.6.3")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin" % "1.0.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"        % "1.4.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "1.9.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.20")
